public class Properties(){
    public int TeamSize;
    public int UnfairTeamSize;
    public int Team0Score;
    public float TotalSecondsPlayed;
    public long MatchStartEpoch;
    public Goal[] Goals;
    public Highlight[] HighLights;
    public PlayerStat[] PlayerStats;
    public string ReplayName;
    public int ReplayVersion;
    public int ReplayLastSaveVersion;
    public int gameVersion;
    public long BuildID;
    public long Changelist;
    public string BuildVersion;
    public int ReserveMegabytes;
    public float RecordFPS;
    public float KeyframeDelay;
    public int MaxChannels;
    public int MaxReplaySizeMB;
    public string Id;
    public string MapName;
    public string Date;
    public int NumFrames;
    public string MatchType;
}