public class Replay(){
    public string? header_size; 
    public string? header_crc;
    public string? major_version;
    public string? minor_version;
    public string? net_version;
    public string? game_type;
    public Properties? properties;
    public string? content_size;
    public string? content_crc;
    public NetworkFrames? network_frames;
    public string[]? levels;
    public Keyframe[]? keyframes;
    public Debug[]? debug_info;
    public TickMark[]? tick_marks;
    public string[]? packages;
    public string[]? objects;
    public string[]? names;
    public ClassIndex[]? class_indices;
}